MONITOREO MENSUAL

In [17]:
#Limpiamos el entorno de trabajo
rm(list = ls())

In [18]:
#Cargamos las librerías necesarias! (Otro día tendré que hacer un archivo para explicar las librerías que más uso)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, srvyr, openxlsx, readr, janitor, dplyr, stringr, googlesheets4, writexl)

Loading required package: pacman

In [19]:
#Base de envío anterior (abril)

url_csv <- "https://docs.google.com/spreadsheets/d/1syM1Z-VbpOmg9WvrzoX9482Pjv130-TM/export?format=csv&gid=501566719"

abril <- read.csv(url_csv) %>%
  clean_names() %>%
  select(nombre_de_la_accion_de_capacitacion, nombre_de_la_persona_servidora_publica) %>%
  rename(capacitacion = nombre_de_la_accion_de_capacitacion,
         persona = nombre_de_la_persona_servidora_publica)
head(abril)

  capacitacion
1 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
2 Inteligencia Artificial para la Vida y el Trabajo
3 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
4 Cumplimiento de la Ley General de Archivos y Normatividad en Materia de Archivos 2026
5 Derechos Humanos y Genero
6 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
  persona
1 Adriana Cecilia Maya Cabrera
2 Adriana Cecilia Maya Cabrera
3 Ana Laura Solís Sala
4 Angel Israel de la Cruz Pérez
5 Brenda Itzel Del Toro Torres
6 Brenda Itzel Del Toro Torres

In [20]:
#Base concentrado

url_csv2 <- "https://docs.google.com/spreadsheets/d/1QsgjKt3mS_OV3suheKVu5Dy6NmwQtvyP/export?format=csv"

concentrado <- read.csv(url_csv2, skip = 2) %>%
  clean_names() %>%
  select(nombre_de_la_accion_de_capacitacion, nombre_de_la_persona_servidora_publica, estatus, estatus_constancia_esta_columna_no_se_llena_por_el_personal) %>%
  rename(capacitacion = nombre_de_la_accion_de_capacitacion,
         persona = nombre_de_la_persona_servidora_publica,
         estatus_constancia = estatus_constancia_esta_columna_no_se_llena_por_el_personal) %>%
  filter(estatus == "Concluido con constancia")
head(concentrado)

  capacitacion
1 Introducción a la ciencia de datos
2 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
3 Inteligencia Artificial para la Vida y el Trabajo
4 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
5 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
6 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
  persona                      estatus                  estatus_constancia
1 Adriana Cabrera Pliego       Concluido con constancia Recibida
2 Adriana Cecilia Maya Cabrera Concluido con constancia No se ha enviado
3 Adriana Cecilia Maya Cabrera Concluido con constancia No se ha enviado
4 Alejandra Martínez Cervantes Concluido con constancia Recibida
5 Ana Laura Solís Sala         Concluido con constancia No se ha enviado
6 Ana Paulina Morales Aguilar  Concluido con constancia Recibida

In [21]:
#Base con la actualización de capacitaciones terminadas pero que no han mandado su constancia
nuevo_mes_faltantes_envio <- anti_join(concentrado, abril, by = c("capacitacion", "persona")) %>%
  filter(estatus_constancia != "Recibida") %>%
  select(persona, capacitacion)
nuevo_mes_faltantes_envio

     persona capacitacion

In [22]:
#Nuevo mes (hayan o no mandado su constancia)
nuevo_mes <- anti_join(concentrado, abril, by = c("capacitacion", "persona"))
nuevo_mes

   capacitacion
1  Introducción a la ciencia de datos
2  Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
3  Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
4  Brecha Salarial de Género
5  Introducción a la Ciberseguridad
6  ¿Cómo reconocer las conductas que NO son consideradas hostigamiento sexual y acoso sexual?
7  Brecha Salarial de Género
8  Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
9  Introducción a la Administración Pública Federal
10 Introducción a la ciberseguridad
11 Reforma constitucional en materia de transparencia y acceso a la información pública
12 Introducción a la Ley General de Transparencia y Acceso a la Información Pública
13 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
14 Reforma constitucional en materia de transparencia y acceso a la información pública
15 Excel Avanzado
16 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
17 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
18 Ética e integridad pública para un Buen Gobierno
19 Brecha Salarial de Género
   persona                            estatus
1  Adriana Cabrera Pliego             Concluido con constancia
2  Alejandra Martínez Cervantes       Concluido con constancia
3  Ana Paulina Morales Aguilar        Concluido con constancia
4  Cecilia Gutiérrez Márquez          Concluido con constancia
5  Hugo Jair López Téllez             Concluido con constancia
6  Hugo Jair López Téllez             Concluido con constancia
7  Hugo Jair López Téllez             Concluido con constancia
8  Israel Rodríguez Casasanero        Concluido con constancia
9  Israel Rodríguez Casasanero        Concluido con constancia
10 Israel Rodríguez Casasanero        Concluido con constancia
11 Jorge Luis Álvarez Peralta         Concluido con constancia
12 Roberto Emmanuel Arroyo San Martin Concluido con constancia
13 Roberto Emmanuel Arroyo San Martin Concluido con constancia
14 Roberto Emmanuel Arroyo San Martin Concluido con constancia
15 Roberto Emmanuel Arroyo San Martin Concluido con constancia
16 Victor Hugo Castellanos Lemus      Concluido con constancia
17 Victor Hugo Castellanos Lemus      Concluido con constancia
18 Victor Hugo Castellanos Lemus      Concluido con constancia
19 Victor Hugo Castellanos Lemus      Concluido con constancia
   estatus_constancia
1  Recibida
2  Recibida
3  Recibida
4  Recibida
5  Recibida
6  Recibida
7  Recibida
8  Recibida
9  Recibida
10 Recibida
11 Recibida
12 Recibida
13 Recibida
14 Recibida
15 Recibida
16 Recibida
17 Recibida
18 Recibida
19 Recibida

In [16]:
write_xlsx(nuevo_mes, "nuevo_mes_colab.xlsx")
#Para descargarla, debo hacer click en la carpeta que está justo a la izquierda
#de esta ventana y ahí debe estar

In [25]:
#Nuevo mes con constancias enviadas
nuevo_mes_final <- anti_join(concentrado, abril, by = c("capacitacion", "persona")) %>%
  filter(estatus_constancia=="Recibida")
nuevo_mes_final

   capacitacion
1  Introducción a la ciencia de datos
2  Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
3  Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
4  Brecha Salarial de Género
5  Introducción a la Ciberseguridad
6  ¿Cómo reconocer las conductas que NO son consideradas hostigamiento sexual y acoso sexual?
7  Brecha Salarial de Género
8  Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
9  Introducción a la Administración Pública Federal
10 Introducción a la ciberseguridad
11 Reforma constitucional en materia de transparencia y acceso a la información pública
12 Introducción a la Ley General de Transparencia y Acceso a la Información Pública
13 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
14 Reforma constitucional en materia de transparencia y acceso a la información pública
15 Excel Avanzado
16 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
17 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
18 Ética e integridad pública para un Buen Gobierno
19 Brecha Salarial de Género
   persona                            estatus
1  Adriana Cabrera Pliego             Concluido con constancia
2  Alejandra Martínez Cervantes       Concluido con constancia
3  Ana Paulina Morales Aguilar        Concluido con constancia
4  Cecilia Gutiérrez Márquez          Concluido con constancia
5  Hugo Jair López Téllez             Concluido con constancia
6  Hugo Jair López Téllez             Concluido con constancia
7  Hugo Jair López Téllez             Concluido con constancia
8  Israel Rodríguez Casasanero        Concluido con constancia
9  Israel Rodríguez Casasanero        Concluido con constancia
10 Israel Rodríguez Casasanero        Concluido con constancia
11 Jorge Luis Álvarez Peralta         Concluido con constancia
12 Roberto Emmanuel Arroyo San Martin Concluido con constancia
13 Roberto Emmanuel Arroyo San Martin Concluido con constancia
14 Roberto Emmanuel Arroyo San Martin Concluido con constancia
15 Roberto Emmanuel Arroyo San Martin Concluido con constancia
16 Victor Hugo Castellanos Lemus      Concluido con constancia
17 Victor Hugo Castellanos Lemus      Concluido con constancia
18 Victor Hugo Castellanos Lemus      Concluido con constancia
19 Victor Hugo Castellanos Lemus      Concluido con constancia
   estatus_constancia
1  Recibida
2  Recibida
3  Recibida
4  Recibida
5  Recibida
6  Recibida
7  Recibida
8  Recibida
9  Recibida
10 Recibida
11 Recibida
12 Recibida
13 Recibida
14 Recibida
15 Recibida
16 Recibida
17 Recibida
18 Recibida
19 Recibida

In [26]:
#BASE FINAL CON CORROBORACIÓN DE ENVÍO DE CONSTANCIAS
write_xlsx(nuevo_mes_final, "nuevo_mes_FINAL_colab.xlsx")
#Para descargarla, debo hacer click en la carpeta que está justo a la izquierda
#de esta ventana y ahí debe estar