<a href="https://colab.research.google.com/github/paumorales480/Cosas-que-hago-jiji/blob/main/nuevo_envio_capacitaciones_DEI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Limpiamos el entorno de trabajo
rm(list = ls())

In [2]:
#Cargamos las librerías necesarias! (Otro día tendré que hacer un archivo para explicar las librerías que más uso)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, srvyr, openxlsx, readr, janitor, dplyr, stringr, googlesheets4, writexl)

Loading required package: pacman

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘pacman’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘remotes’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘minqa’, ‘numDeriv’, ‘mitools’, ‘RcppArmadillo’, ‘survey’



srvyr installed

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)


openxlsx installed

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘snakecase’



janitor installed

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)


writexl installed

In [9]:
# ===== CONCENTRADO =========

url_csv <- "https://docs.google.com/spreadsheets/d/1QsgjKt3mS_OV3suheKVu5Dy6NmwQtvyP/export?format=csv&gid=469847885"

concentrado <- read.csv(url_csv, skip = 2) %>%
  clean_names()

head(concentrado)

  estatus_constancia_esta_columna_no_se_llena_por_el_personal mes
1                                                             Abril
2                                                             Abril
3                                                             Abril
4                                                             Abril
5 Recibida                                                    Abril
6 No se ha enviado                                            Marzo
  estatus
1 Inscrito
2 Inscrito
3 Inscrito
4 Inscrito
5 Concluido con constancia
6 Concluido con constancia
  nombre_de_la_accion_de_capacitacion
1 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
2 Como crear y administrar un curso de Moodle
3 Fundamentos del Power BI
4 Introducción a la Programación con Python
5 Introducción a la ciencia de datos
6 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
  nombre_de_la_persona_servidora_publica comite_de_transparencia
1 Adriana Cabrera Pliego                 NA
2 Adriana Cabrera Pliego                 NA
3 Adriana Cabrera Pliego                 NA
4 Adriana Cabrera Pliego                 NA
5 Adriana Cabrera Pliego                 NA
6 Adriana Cecilia Maya Cabrera           NA
  unidad_de_transparencia enlace_de_portal_de_obligaciones_de_transparencia
1 NA                      NA
2 NA                      NA
3 NA                      NA
4 NA                      NA
5 NA                      NA
6 NA                      NA
  enlace_de_transparencia otras_personas_servidoras_publicas total
1 NA                      1                                  1
2 NA                                                         0
3 NA                                                         0
4 NA                                                         0
5 NA                                                         0
6 NA                      1                                  1
  mando_superior mando_medio operativos total_1
1 NA              1          NA         1
2 NA             NA          NA         0
3 NA             NA          NA         0
4 NA             NA          NA         0
5 NA             NA          NA         0
6 NA              1          NA         1

In [11]:
#=========== CONCENTRADO DE ENVÍOS DE ABRIL Y MAYO ======

url2_csv <- "https://docs.google.com/spreadsheets/d/14bp0fler6xTbOQY8YO_ETipTOp7qwiF5/export?format=csv&gid=501566719"

envios <- read.csv(url2_csv) %>%
  clean_names()

head(envios)

  nombre_de_la_accion_de_capacitacion
1 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
2 Inteligencia Artificial para la Vida y el Trabajo
3 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
4 Cumplimiento de la Ley General de Archivos y Normatividad en Materia de Archivos 2026
5 Derechos Humanos y Genero
6 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
  nombre_de_la_persona_servidora_publica comite_de_transparencia
1 Adriana Cecilia Maya Cabrera           NA
2 Adriana Cecilia Maya Cabrera           NA
3 Ana Laura Solís Sala                   NA
4 Angel Israel de la Cruz Pérez          NA
5 Brenda Itzel Del Toro Torres           NA
6 Brenda Itzel Del Toro Torres           NA
  unidad_de_transparencia enlace_de_portal_de_obligaciones_de_transparencia
1 NA                      NA
2 NA                      NA
3 NA                      NA
4 NA                      NA
5 NA                      NA
6 NA                      NA
  enlace_de_transparencia otras_personas_servidoras_publicas total
1 NA                      1                                  1
2 NA                      1                                  1
3 NA                      1                                  1
4 NA                      1                                  1
5 NA                      1                                  1
6 NA                      1                                  1
  mando_superior mando_medio operoativos total_1
1 NA              1          NA          1
2 NA              1          NA          1
3 NA              1          NA          1
4 NA             NA           1          1
5 NA              1          NA          1
6 NA              1          NA          1

In [12]:
names(concentrado)

 [1] "estatus_constancia_esta_columna_no_se_llena_por_el_personal"
 [2] "mes"
 [3] "estatus"
 [4] "nombre_de_la_accion_de_capacitacion"
 [5] "nombre_de_la_persona_servidora_publica"
 [6] "comite_de_transparencia"
 [7] "unidad_de_transparencia"
 [8] "enlace_de_portal_de_obligaciones_de_transparencia"
 [9] "enlace_de_transparencia"
[10] "otras_personas_servidoras_publicas"
[11] "total"
[12] "mando_superior"
[13] "mando_medio"
[14] "operativos"
[15] "total_1"

In [19]:
#Limpieza de bases

l_concentrado <- concentrado %>%
  rename(estatus_constancia = estatus_constancia_esta_columna_no_se_llena_por_el_personal,
          nombre = nombre_de_la_persona_servidora_publica,
          capacitacion = nombre_de_la_accion_de_capacitacion) %>%
  select(estatus_constancia, nombre, estatus, capacitacion) %>%
  filter(estatus == "Concluido con constancia")

tail(l_concentrado)

   estatus_constancia nombre                        estatus
42 Recibida           Victor Hugo Castellanos Lemus Concluido con constancia
43 Recibida           Victor Hugo Castellanos Lemus Concluido con constancia
44 Recibida           Victor Hugo Castellanos Lemus Concluido con constancia
45 Recibida           Victor Hugo Castellanos Lemus Concluido con constancia
46 Recibida           Victor Hugo Castellanos Lemus Concluido con constancia
47 Recibida           Victor Hugo Castellanos Lemus Concluido con constancia
   capacitacion
42 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
43 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
44 Igualdad de Género y comunicación incluyente
45 Reforma Constitucional en Materia de Transparencia y Acceso a la Información Pública
46 Ética e integridad pública para un Buen Gobierno
47 Brecha Salarial de Género

In [21]:
names(envios)

 [1] "nombre_de_la_accion_de_capacitacion"
 [2] "nombre_de_la_persona_servidora_publica"
 [3] "comite_de_transparencia"
 [4] "unidad_de_transparencia"
 [5] "enlace_de_portal_de_obligaciones_de_transparencia"
 [6] "enlace_de_transparencia"
 [7] "otras_personas_servidoras_publicas"
 [8] "total"
 [9] "mando_superior"
[10] "mando_medio"
[11] "operoativos"
[12] "total_1"

In [22]:
#===== Limpieza de envios ==
l_envios <- envios %>%
  rename(capacitacion = nombre_de_la_accion_de_capacitacion,
        nombre = nombre_de_la_persona_servidora_publica)
head(l_envios)

  capacitacion
1 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
2 Inteligencia Artificial para la Vida y el Trabajo
3 Introducción al Órgano Administrativo Desconcentrado Transparencia para el Pueblo
4 Cumplimiento de la Ley General de Archivos y Normatividad en Materia de Archivos 2026
5 Derechos Humanos y Genero
6 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
  nombre                        comite_de_transparencia unidad_de_transparencia
1 Adriana Cecilia Maya Cabrera  NA                      NA
2 Adriana Cecilia Maya Cabrera  NA                      NA
3 Ana Laura Solís Sala          NA                      NA
4 Angel Israel de la Cruz Pérez NA                      NA
5 Brenda Itzel Del Toro Torres  NA                      NA
6 Brenda Itzel Del Toro Torres  NA                      NA
  enlace_de_portal_de_obligaciones_de_transparencia enlace_de_transparencia
1 NA                                                NA
2 NA                                                NA
3 NA                                                NA
4 NA                                                NA
5 NA                                                NA
6 NA                                                NA
  otras_personas_servidoras_publicas total mando_superior mando_medio
1 1                                  1     NA              1
2 1                                  1     NA              1
3 1                                  1     NA              1
4 1                                  1     NA             NA
5 1                                  1     NA              1
6 1                                  1     NA              1
  operoativos total_1
1 NA          1
2 NA          1
3 NA          1
4  1          1
5 NA          1
6 NA          1

In [24]:
names(envios)

 [1] "nombre_de_la_accion_de_capacitacion"
 [2] "nombre_de_la_persona_servidora_publica"
 [3] "comite_de_transparencia"
 [4] "unidad_de_transparencia"
 [5] "enlace_de_portal_de_obligaciones_de_transparencia"
 [6] "enlace_de_transparencia"
 [7] "otras_personas_servidoras_publicas"
 [8] "total"
 [9] "mando_superior"
[10] "mando_medio"
[11] "operoativos"
[12] "total_1"

In [26]:
# Quitar del concentrado las que no estan en envios
nuevos_registros <- anti_join(l_concentrado, l_envios, by=c("capacitacion", "nombre"))

print(nuevos_registros)

  estatus_constancia                        nombre                  estatus
1           Recibida  Alejandra Martínez Cervantes Concluido con constancia
2           Recibida  Alejandra Martínez Cervantes Concluido con constancia
3           Recibida          Ana Laura Solís Sala Concluido con constancia
4           Recibida          Ana Laura Solís Sala Concluido con constancia
5           Recibida          Ana Laura Solís Sala Concluido con constancia
6           Recibida          Ana Laura Solís Sala Concluido con constancia
7           Recibida  Ana Paulina Morales Aguilar  Concluido con constancia
8           Recibida    Jorge Luis Álvarez Peralta Concluido con constancia
9           Recibida Victor Hugo Castellanos Lemus Concluido con constancia
                                                     capacitacion
1               Introducción a la Administración Pública Federal
2                Ética e integridad pública para un buen gobierno
3                        Cómo cerrar la brecha salarial de género
4                    Igualdad de género y comunicación incluyente
5 Masculinidades ¿nuevas, positivas,\ndeconstruidas o emergentes?
6                             Hostigamiento sexual y acoso sexual
7                    Igualdad de Género y comunicación incluyente
8                                Introducción a la Ciberseguridad
9                    Igualdad de Género y comunicación incluyente

In [28]:
#Exportamos la nueva base

write_xlsx(nuevos_registros, "nuevos_registros.xlsx")

In [37]:
#========== Personas con capacitación registrada como concluida
#           pero no ha mandado su constancia


faltantes <- concentrado %>%
  rename(estatus_constancia = estatus_constancia_esta_columna_no_se_llena_por_el_personal,
        capacitacion = nombre_de_la_accion_de_capacitacion,
        nombre= nombre_de_la_persona_servidora_publica) %>%
  select(estatus_constancia, estatus, nombre, capacitacion) %>%
  filter(estatus_constancia == "No se ha enviado ")
faltantes

  estatus_constancia estatus                  nombre
1 No se ha enviado   Concluido con constancia Adriana Cecilia Maya Cabrera
2 No se ha enviado   Concluido con constancia Adriana Cecilia Maya Cabrera
3 No se ha enviado   Concluido con constancia Brenda Itzel Del Toro Torres
4 No se ha enviado   Concluido con constancia Brenda Itzel Del Toro Torres
5 No se ha enviado   Concluido con constancia Brenda Itzel Del Toro Torres
  capacitacion
1 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
2 Inteligencia Artificial para la Vida y el Trabajo
3 Derechos Humanos y Genero
4 Buenas prácticas de Transparencia y el ejercicio del Derecho de Acceso a la Información Pública en la Administración Pública Federal
5 Reforma constitucional en materia de transparencia y acceso a la información pública

In [38]:
# Exportamos faltantes de envíos
write_xlsx(faltantes, "Faltantes.xlsx")